ARG version
FROM almalinux:${version:-8}
# RUN cat /etc/*release
ARG COURSE=Docker
ARG TRAINER=Siva
ENV Duration=120hrs
RUN echo "Course is : ${COURSE}, Trainer is : ${TRAINER}, Duration is ${DURATION}"
CMD ["sleep","200"]
